# Directories
directories:
  raw: "data/raw"
  reference: "data/reference"
  qc: "results/qc"
  trim: "data/trim"
  align: "results/align"

# Paramaters
params:
  download-threads: 1
  qc-threads: 4
  trim-threads: 4
  count-threads: 4
  align-threads: 8
  phred-cutoff: 20
  hisat2-index-url: "https://genome-idx.s3.amazonaws.com/hisat/grch38_tran.tar.gz"
